spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # create-drop : SessionFactory가 시작될때 Drop을 하고, Create, Alter 종료될때 Dropd
      # SpringBoot 서버가 시작될 때마다 테이블들이 새로 만들어지기 때문에, 편의를 위해서 서버를 시작할때마다 Data를 자동으로 DB에 넣어주는 기능 활용
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        # 콘솔창에서 실행되는 SQL을 보기좋게 보여주는 설정 추가
    defer-datasource-initialization: true

logging:
  level:
    io.zurijang: DEBUG